#firefly:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10  
  # Position Controllers ---------------------------------------
  camera_pitch_controller:
    type: effort_controllers/JointPositionController
    joint: camera_pitch_control_joint
    pid: {p: 3.5, i: 0.01, d: 0.1}
  camera_roll_controller:
    type: effort_controllers/JointPositionController
    joint: camera_roll_control_joint
    pid: {p: 2.0, i: 0.01, d: 0.1}
